# Generated by Django 5.2.4 on 2025-07-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Magazyn',
                'verbose_name_plural': 'Magazyny',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='NazwaUrzadzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nazwa urządzenia',
                'verbose_name_plural': 'Nazwy urządzeń',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Czesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_seryjny', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('klient_nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_zgloszenia', models.CharField(blank=True, max_length=100, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('magazyn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='czesci', to='magazyn_core.magazyn')),
                ('nazwa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='magazyn_core.nazwaurzadzenia')),
            ],
            options={
                'verbose_name': 'Część',
                'verbose_name_plural': 'Części',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OperacjaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_operacji', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('data_operacji', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log operacji',
                'verbose_name_plural': 'Logi operacji',
                'ordering': ['-data_operacji'],
            },
        ),
        migrations.CreateModel(
            name='ModelUrzadzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('producent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modele', to='magazyn_core.producent')),
            ],
            options={
                'verbose_name': 'Model urządzenia',
                'verbose_name_plural': 'Modele urządzeń',
                'ordering': ['producent__nazwa', 'nazwa'],
                'unique_together': {('nazwa', 'producent')},
            },
        ),
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_seryjny', models.CharField(max_length=100, unique=True)),
                ('indeks_dodatkowy', models.CharField(blank=True, max_length=100, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('na_stale', models.BooleanField(default=False)),
                ('klient_nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_zgloszenia', models.CharField(blank=True, max_length=100, null=True)),
                ('magazyn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urzadzenia', to='magazyn_core.magazyn')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urzadzenia', to='magazyn_core.modelurzadzenia')),
                ('nazwa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='magazyn_core.nazwaurzadzenia')),
                ('producent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urzadzenia', to='magazyn_core.producent')),
            ],
            options={
                'verbose_name': 'Urządzenie',
                'verbose_name_plural': 'Urządzenia',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PrzesuniecieMagazynowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przesuniecia', models.DateTimeField(auto_now_add=True)),
                ('magazyn_docelowy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='przesuniecia_docelowe', to='magazyn_core.magazyn')),
                ('magazyn_zrodlowy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='przesuniecia_zrodlowe', to='magazyn_core.magazyn')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('urzadzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przesuniecia', to='magazyn_core.urzadzenie')),
            ],
            options={
                'verbose_name': 'Przesunięcie magazynowe',
                'verbose_name_plural': 'Przesunięcia magazynowe',
                'ordering': ['-data_przesuniecia'],
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient_nazwa', models.CharField(max_length=100)),
                ('numer_zgloszenia', models.CharField(max_length=100)),
                ('urzadzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczenia', to='magazyn_core.urzadzenie')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
                'ordering': ['-id'],
            },
        ),
    ]
