# Generated by Django 5.2.4 on 2025-07-06 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn_core', '0002_alter_czesc_numer_seryjny'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenie',
            name='data_wypozyczenia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
