# Generated by Django 5.2.4 on 2025-07-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn_core', '0003_wypozyczenie_data_wypozyczenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiwumUrzadzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_seryjny', models.CharField(max_length=100)),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('klient_nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_zgloszenia', models.CharField(blank=True, max_length=100, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('data_przekazania', models.DateTimeField(auto_now_add=True)),
                ('magazyn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazyn_core.magazyn')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazyn_core.modelurzadzenia')),
                ('nazwa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazyn_core.nazwaurzadzenia')),
                ('producent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazyn_core.producent')),
            ],
            options={
                'verbose_name': 'Przekazane urządzenie (archiwum)',
                'verbose_name_plural': 'Archiwum urządzeń przekazanych',
                'ordering': ['-data_przekazania'],
            },
        ),
    ]
